services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/inventory-service/database:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  inventory-service:
    build: ./services/inventory-service
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "${INVENTORY_PORT}:${INVENTORY_PORT}"

  history-service:
    build: ./services/history-service
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "${HISTORY_PORT}:${HISTORY_PORT}"


volumes:
  postgres_data: