services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "${DATABASE_NAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
    ports:
      - "$DATABASE_PORT:$DATABASE_PORT"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: ./user-service
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    env_file: .env
    command: sh -c "npm run migration:run && npm run start:prod"

volumes:
  postgres_data: